import {
  LayoutGrid,
  Building2,
  Layers,
  Clock,
  UserPlus2,
  CalendarDays,
  Users2,
  Video,
  Bell,
  Settings,
  Stethoscope,
  FileBarChart,
  CalendarX2,
  ShieldCheck,
} from "lucide-vue-next";

export default {
  theme: {
    title: "Smart Care",
    subtitle: "Hospital Admin",
    background: "bg-white",
  },

  menu: [
    {
      titleKey: "nav.dashboard",
      title: "Dashboard",
      route: "/hospital-admin/dashboard",
      icon: LayoutGrid,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.departments",
      title: "Departments",
      route: "/hospital-admin/departments",
      icon: Building2,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.facilities",
      title: "Facilities",
      route: "/hospital-admin/facilities",
      icon: Layers,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.operating_hours",
      title: "Operating Hours",
      route: "/hospital-admin/operating-hours",
      icon: Clock,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.doctors_staff",
      title: "Doctors & Staff",
      route: "/hospital-admin/doctors",
      icon: UserPlus2,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.appointments",
      title: "Appointments",
      route: "/hospital-admin/appointments",
      icon: CalendarDays,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.queue_management",
      title: "Queue Management",
      route: "/hospital-admin/queue",
      icon: Users2,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.telemedicine",
      title: "Telemedicine",
      route: "/hospital-admin/telemanagment",
      icon: Video,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.doctor_leaves",
      title: "Doctor Leaves",
      route: "/hospital-admin/leaves",
      icon: CalendarX2,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.notifications",
      title: "Notifications",
      route: "/hospital-admin/notifications",
      icon: Bell,
      roles: ["hospital_admin"],
    },
    // {
    //   titleKey: "nav.settings",
    //   title: "Settings",
    //   route: "/settings",
    //   icon: Settings,
    //   roles: ["hospital_admin"],
    // },
    {
      titleKey: "nav.reports_analytics",
      title: "Reports & Analytics",
      route: "/hospital-admin/reports",
      icon: FileBarChart,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.symptoms",
      title: "Symptoms",
      route: "/hospital-admin/symptoms",
      icon: Stethoscope,
      roles: ["hospital_admin"],
    },
    {
      titleKey: "nav.roles_permissions",
      title: "Roles & Permissions",
      route: "/hospital-admin/role",
      icon: ShieldCheck,
      roles: ["hospital_admin"],
    },
  ],
};
